Traceback (most recent call last):
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pewhite/.asdf/installs/python/3.11.9/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
M = np.random.normal(0,1,(2,2))/np.linalg.norm(M)
p = np.vstack([X,Y])
X2,Y2 = M@p
ax = plt.gca()
ax.scatter(X2,Y2,s=0.2)
ax.set_aspect(1)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m M [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39mnormal([38;5;241m0[39m,[38;5;241m1[39m,([38;5;241m2[39m,[38;5;241m2[39m))[38;5;241m/[39mnp[38;5;241m.[39mlinalg[38;5;241m.[39mnorm([43mM[49m)
[1;32m      2[0m p [38;5;241m=[39m np[38;5;241m.[39mvstack([X,Y])
[1;32m      3[0m X2,Y2 [38;5;241m=[39m M[38;5;129m@p[39m

[0;31mNameError[0m: name 'M' is not defined

